
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class Abilities : Luban.BeanBase
{
    public Abilities(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["AbilityEnum"].IsString) { throw new SerializationException(); }  AbilityEnum = _buf["AbilityEnum"]; }
    }

    public static Abilities DeserializeAbilities(JSONNode _buf)
    {
        return new Battle.Abilities(_buf);
    }

    /// <summary>
    /// id 
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 能力枚举
    /// </summary>
    public readonly string AbilityEnum;
   
    public const int __ID__ = 1548117394;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "AbilityEnum:" + AbilityEnum + ","
        + "}";
    }
}
}

