
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class CharacterInfo : Luban.BeanBase
{
    public CharacterInfo(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { var __json0 = _buf["Abilities"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Abilities = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Abilities[__index0++] = __v0; }   }
    }

    public static CharacterInfo DeserializeCharacterInfo(JSONNode _buf)
    {
        return new Battle.CharacterInfo(_buf);
    }

    /// <summary>
    /// id 
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 能力
    /// </summary>
    public readonly int[] Abilities;
   
    public const int __ID__ = 1010443457;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Abilities:" + Luban.StringUtil.CollectionToString(Abilities) + ","
        + "}";
    }
}
}

