
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public sealed partial class Guide : Luban.BeanBase
{
    public Guide(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Text"].IsString) { throw new SerializationException(); }  Text = _buf["Text"]; }
    }

    public static Guide DeserializeGuide(JSONNode _buf)
    {
        return new Battle.Guide(_buf);
    }

    /// <summary>
    /// id 
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 文本
    /// </summary>
    public readonly string Text;
   
    public const int __ID__ = 1261466182;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Text:" + Text + ","
        + "}";
    }
}
}

