
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TbCharacterInfo
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.CharacterInfo> _dataMap;
    private readonly System.Collections.Generic.List<Battle.CharacterInfo> _dataList;
    
    public TbCharacterInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.CharacterInfo>(count);
        _dataList = new System.Collections.Generic.List<Battle.CharacterInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.CharacterInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Battle.CharacterInfo.DeserializeCharacterInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.CharacterInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.CharacterInfo> DataList => _dataList;

    public Battle.CharacterInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.CharacterInfo Get(int key) => _dataMap[key];
    public Battle.CharacterInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

