
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Battle
{
public partial class TbGuide
{
    private readonly System.Collections.Generic.Dictionary<int, Battle.Guide> _dataMap;
    private readonly System.Collections.Generic.List<Battle.Guide> _dataList;
    
    public TbGuide(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Battle.Guide>(count);
        _dataList = new System.Collections.Generic.List<Battle.Guide>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Battle.Guide _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Battle.Guide.DeserializeGuide(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Battle.Guide> DataMap => _dataMap;
    public System.Collections.Generic.List<Battle.Guide> DataList => _dataList;

    public Battle.Guide GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Battle.Guide Get(int key) => _dataMap[key];
    public Battle.Guide this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

