
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 角色配置
/// </summary>
public sealed partial class CharacterInfo : Luban.BeanBase
{
    public CharacterInfo(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["CharacterId"].IsString) { throw new SerializationException(); }  CharacterId = _buf["CharacterId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["CharacterClass"].IsNumber) { throw new SerializationException(); }  CharacterClass = _buf["CharacterClass"]; }
        { if(!_buf["BaseHp"].IsNumber) { throw new SerializationException(); }  BaseHp = _buf["BaseHp"]; }
        { if(!_buf["BaseAtk"].IsNumber) { throw new SerializationException(); }  BaseAtk = _buf["BaseAtk"]; }
        { if(!_buf["BaseDef"].IsNumber) { throw new SerializationException(); }  BaseDef = _buf["BaseDef"]; }
        { if(!_buf["BaseSpd"].IsNumber) { throw new SerializationException(); }  BaseSpd = _buf["BaseSpd"]; }
        { if(!_buf["BaseCritRate"].IsNumber) { throw new SerializationException(); }  BaseCritRate = _buf["BaseCritRate"]; }
        { if(!_buf["BaseCritDmg"].IsNumber) { throw new SerializationException(); }  BaseCritDmg = _buf["BaseCritDmg"]; }
        { if(!_buf["HpPerLevel"].IsNumber) { throw new SerializationException(); }  HpPerLevel = _buf["HpPerLevel"]; }
        { if(!_buf["AtkPerLevel"].IsNumber) { throw new SerializationException(); }  AtkPerLevel = _buf["AtkPerLevel"]; }
        { if(!_buf["DefPerLevel"].IsNumber) { throw new SerializationException(); }  DefPerLevel = _buf["DefPerLevel"]; }
        { if(!_buf["SpdPerLevel"].IsNumber) { throw new SerializationException(); }  SpdPerLevel = _buf["SpdPerLevel"]; }
        { if(!_buf["BaseExpToLevel"].IsNumber) { throw new SerializationException(); }  BaseExpToLevel = _buf["BaseExpToLevel"]; }
        { if(!_buf["ExpGrowthFactor"].IsNumber) { throw new SerializationException(); }  ExpGrowthFactor = _buf["ExpGrowthFactor"]; }
        { if(!_buf["MaxLevel"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["MaxLevel"]; }
    }

    public static CharacterInfo DeserializeCharacterInfo(JSONNode _buf)
    {
        return new Adventure.CharacterInfo(_buf);
    }

    /// <summary>
    /// 角色ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 角色字符串ID
    /// </summary>
    public readonly string CharacterId;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 职业(0战士/1法师/2弓手/3治疗)
    /// </summary>
    public readonly int CharacterClass;
    /// <summary>
    /// 1级生命值
    /// </summary>
    public readonly float BaseHp;
    /// <summary>
    /// 1级攻击力
    /// </summary>
    public readonly float BaseAtk;
    /// <summary>
    /// 1级防御力
    /// </summary>
    public readonly float BaseDef;
    /// <summary>
    /// 攻击速度
    /// </summary>
    public readonly float BaseSpd;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float BaseCritRate;
    /// <summary>
    /// 暴击伤害倍率
    /// </summary>
    public readonly float BaseCritDmg;
    /// <summary>
    /// 每级生命成长
    /// </summary>
    public readonly float HpPerLevel;
    /// <summary>
    /// 每级攻击成长
    /// </summary>
    public readonly float AtkPerLevel;
    /// <summary>
    /// 每级防御成长
    /// </summary>
    public readonly float DefPerLevel;
    /// <summary>
    /// 每级速度成长
    /// </summary>
    public readonly float SpdPerLevel;
    /// <summary>
    /// 升到2级所需经验
    /// </summary>
    public readonly int BaseExpToLevel;
    /// <summary>
    /// 经验递增系数
    /// </summary>
    public readonly float ExpGrowthFactor;
    /// <summary>
    /// 最大等级
    /// </summary>
    public readonly int MaxLevel;
   
    public const int __ID__ = 611087577;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "CharacterId:" + CharacterId + ","
        + "Name:" + Name + ","
        + "CharacterClass:" + CharacterClass + ","
        + "BaseHp:" + BaseHp + ","
        + "BaseAtk:" + BaseAtk + ","
        + "BaseDef:" + BaseDef + ","
        + "BaseSpd:" + BaseSpd + ","
        + "BaseCritRate:" + BaseCritRate + ","
        + "BaseCritDmg:" + BaseCritDmg + ","
        + "HpPerLevel:" + HpPerLevel + ","
        + "AtkPerLevel:" + AtkPerLevel + ","
        + "DefPerLevel:" + DefPerLevel + ","
        + "SpdPerLevel:" + SpdPerLevel + ","
        + "BaseExpToLevel:" + BaseExpToLevel + ","
        + "ExpGrowthFactor:" + ExpGrowthFactor + ","
        + "MaxLevel:" + MaxLevel + ","
        + "}";
    }
}
}

