
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Adventure
{ 
    /// <summary>
    /// 角色职业
    /// </summary>
    public enum ECharacterClass
    {
        /// <summary>
        /// 战士
        /// </summary>
        Warrior = 0,
        /// <summary>
        /// 法师
        /// </summary>
        Mage = 1,
        /// <summary>
        /// 弓箭手
        /// </summary>
        Archer = 2,
        /// <summary>
        /// 治疗
        /// </summary>
        Healer = 3,
    }

} 

