
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Adventure
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum EItemType
    {
        /// <summary>
        /// 消耗品
        /// </summary>
        Consumable = 0,
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 1,
        /// <summary>
        /// 材料
        /// </summary>
        Material = 2,
        /// <summary>
        /// 任务道具
        /// </summary>
        Quest = 3,
        /// <summary>
        /// 杂物
        /// </summary>
        Misc = 4,
    }

} 

