
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Adventure
{ 
    /// <summary>
    /// 道具品质
    /// </summary>
    public enum EItemRarity
    {
        /// <summary>
        /// 普通
        /// </summary>
        Common = 0,
        /// <summary>
        /// 优秀
        /// </summary>
        Uncommon = 1,
        /// <summary>
        /// 稀有
        /// </summary>
        Rare = 2,
        /// <summary>
        /// 史诗
        /// </summary>
        Epic = 3,
        /// <summary>
        /// 传说
        /// </summary>
        Legendary = 4,
    }

} 

