
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Adventure
{ 
    /// <summary>
    /// 地点类型
    /// </summary>
    public enum ELocationType
    {
        /// <summary>
        /// 冒险者公会
        /// </summary>
        AdventurerGuild = 0,
        /// <summary>
        /// 战斗区域
        /// </summary>
        BattleArea = 1,
        /// <summary>
        /// 任务公告板
        /// </summary>
        QuestBoard = 2,
        /// <summary>
        /// 商店
        /// </summary>
        Shop = 3,
        /// <summary>
        /// 铁匠铺
        /// </summary>
        Blacksmith = 4,
        /// <summary>
        /// 酒馆
        /// </summary>
        Tavern = 5,
    }

} 

