
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Adventure
{ 
    /// <summary>
    /// 任务条件类型
    /// </summary>
    public enum EQuestConditionType
    {
        /// <summary>
        /// 击杀敌人
        /// </summary>
        KillEnemy = 0,
        /// <summary>
        /// 收集物品
        /// </summary>
        CollectItem = 1,
        /// <summary>
        /// 到达区域
        /// </summary>
        ReachArea = 2,
        /// <summary>
        /// 与NPC对话
        /// </summary>
        TalkToNPC = 3,
        /// <summary>
        /// 通关关卡
        /// </summary>
        ClearLevel = 4,
    }

} 

