
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Adventure
{ 
    /// <summary>
    /// 奖励类型
    /// </summary>
    public enum ERewardType
    {
        /// <summary>
        /// 金币
        /// </summary>
        Gold = 0,
        /// <summary>
        /// 经验
        /// </summary>
        Exp = 1,
        /// <summary>
        /// 道具
        /// </summary>
        Item = 2,
        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 3,
    }

} 

