
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 道具配置
/// </summary>
public sealed partial class ItemInfo : Luban.BeanBase
{
    public ItemInfo(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["ItemId"].IsString) { throw new SerializationException(); }  ItemId = _buf["ItemId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
        { if(!_buf["ItemType"].IsNumber) { throw new SerializationException(); }  ItemType = _buf["ItemType"]; }
        { if(!_buf["Rarity"].IsNumber) { throw new SerializationException(); }  Rarity = _buf["Rarity"]; }
        { if(!_buf["MaxStack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["MaxStack"]; }
        { if(!_buf["BuyPrice"].IsNumber) { throw new SerializationException(); }  BuyPrice = _buf["BuyPrice"]; }
        { if(!_buf["SellPrice"].IsNumber) { throw new SerializationException(); }  SellPrice = _buf["SellPrice"]; }
        { if(!_buf["HealAmount"].IsNumber) { throw new SerializationException(); }  HealAmount = _buf["HealAmount"]; }
        { if(!_buf["EffectId"].IsString) { throw new SerializationException(); }  EffectId = _buf["EffectId"]; }
    }

    public static ItemInfo DeserializeItemInfo(JSONNode _buf)
    {
        return new Adventure.ItemInfo(_buf);
    }

    /// <summary>
    /// 道具ID(主键)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具字符串ID
    /// </summary>
    public readonly string ItemId;
    /// <summary>
    /// 道具名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int ItemType;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Rarity;
    /// <summary>
    /// 最大堆叠数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 购买价格
    /// </summary>
    public readonly int BuyPrice;
    /// <summary>
    /// 出售价格
    /// </summary>
    public readonly int SellPrice;
    /// <summary>
    /// 恢复量
    /// </summary>
    public readonly int HealAmount;
    /// <summary>
    /// 效果ID
    /// </summary>
    public readonly string EffectId;
   
    public const int __ID__ = 439394239;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ItemId:" + ItemId + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "ItemType:" + ItemType + ","
        + "Rarity:" + Rarity + ","
        + "MaxStack:" + MaxStack + ","
        + "BuyPrice:" + BuyPrice + ","
        + "SellPrice:" + SellPrice + ","
        + "HealAmount:" + HealAmount + ","
        + "EffectId:" + EffectId + ","
        + "}";
    }
}
}

