
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 地点配置
/// </summary>
public sealed partial class LocationInfo : Luban.BeanBase
{
    public LocationInfo(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["LocationId"].IsString) { throw new SerializationException(); }  LocationId = _buf["LocationId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
        { if(!_buf["LocationType"].IsNumber) { throw new SerializationException(); }  LocationType = _buf["LocationType"]; }
        { if(!_buf["UnlockLevel"].IsNumber) { throw new SerializationException(); }  UnlockLevel = _buf["UnlockLevel"]; }
    }

    public static LocationInfo DeserializeLocationInfo(JSONNode _buf)
    {
        return new Adventure.LocationInfo(_buf);
    }

    /// <summary>
    /// 地点ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 地点字符串ID
    /// </summary>
    public readonly string LocationId;
    /// <summary>
    /// 地点名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 地点类型
    /// </summary>
    public readonly int LocationType;
    /// <summary>
    /// 解锁等级
    /// </summary>
    public readonly int UnlockLevel;
   
    public const int __ID__ = 434488417;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LocationId:" + LocationId + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "LocationType:" + LocationType + ","
        + "UnlockLevel:" + UnlockLevel + ","
        + "}";
    }
}
}

