
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 任务条件配置
/// </summary>
public sealed partial class QuestConditionCfg : Luban.BeanBase
{
    public QuestConditionCfg(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["QuestId"].IsString) { throw new SerializationException(); }  QuestId = _buf["QuestId"]; }
        { if(!_buf["ConditionType"].IsNumber) { throw new SerializationException(); }  ConditionType = _buf["ConditionType"]; }
        { if(!_buf["TargetId"].IsString) { throw new SerializationException(); }  TargetId = _buf["TargetId"]; }
        { if(!_buf["RequiredAmount"].IsNumber) { throw new SerializationException(); }  RequiredAmount = _buf["RequiredAmount"]; }
    }

    public static QuestConditionCfg DeserializeQuestConditionCfg(JSONNode _buf)
    {
        return new Adventure.QuestConditionCfg(_buf);
    }

    /// <summary>
    /// 条件ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属任务ID
    /// </summary>
    public readonly string QuestId;
    /// <summary>
    /// 条件类型
    /// </summary>
    public readonly int ConditionType;
    /// <summary>
    /// 目标ID
    /// </summary>
    public readonly string TargetId;
    /// <summary>
    /// 需求数量
    /// </summary>
    public readonly int RequiredAmount;
   
    public const int __ID__ = 851642285;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "QuestId:" + QuestId + ","
        + "ConditionType:" + ConditionType + ","
        + "TargetId:" + TargetId + ","
        + "RequiredAmount:" + RequiredAmount + ","
        + "}";
    }
}
}

