
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 任务配置
/// </summary>
public sealed partial class QuestInfo : Luban.BeanBase
{
    public QuestInfo(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["QuestId"].IsString) { throw new SerializationException(); }  QuestId = _buf["QuestId"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
        { if(!_buf["RecommendLevel"].IsNumber) { throw new SerializationException(); }  RecommendLevel = _buf["RecommendLevel"]; }
        { if(!_buf["PrerequisiteQuestId"].IsString) { throw new SerializationException(); }  PrerequisiteQuestId = _buf["PrerequisiteQuestId"]; }
    }

    public static QuestInfo DeserializeQuestInfo(JSONNode _buf)
    {
        return new Adventure.QuestInfo(_buf);
    }

    /// <summary>
    /// 任务ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 任务字符串ID
    /// </summary>
    public readonly string QuestId;
    /// <summary>
    /// 任务名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 推荐等级
    /// </summary>
    public readonly int RecommendLevel;
    /// <summary>
    /// 前置任务ID
    /// </summary>
    public readonly string PrerequisiteQuestId;
   
    public const int __ID__ = 1114787602;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "QuestId:" + QuestId + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "RecommendLevel:" + RecommendLevel + ","
        + "PrerequisiteQuestId:" + PrerequisiteQuestId + ","
        + "}";
    }
}
}

