
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 任务奖励配置
/// </summary>
public sealed partial class QuestRewardCfg : Luban.BeanBase
{
    public QuestRewardCfg(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["QuestId"].IsString) { throw new SerializationException(); }  QuestId = _buf["QuestId"]; }
        { if(!_buf["RewardType"].IsNumber) { throw new SerializationException(); }  RewardType = _buf["RewardType"]; }
        { if(!_buf["RewardId"].IsString) { throw new SerializationException(); }  RewardId = _buf["RewardId"]; }
        { if(!_buf["Amount"].IsNumber) { throw new SerializationException(); }  Amount = _buf["Amount"]; }
    }

    public static QuestRewardCfg DeserializeQuestRewardCfg(JSONNode _buf)
    {
        return new Adventure.QuestRewardCfg(_buf);
    }

    /// <summary>
    /// 奖励ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属任务ID
    /// </summary>
    public readonly string QuestId;
    /// <summary>
    /// 奖励类型
    /// </summary>
    public readonly int RewardType;
    /// <summary>
    /// 奖励物品ID
    /// </summary>
    public readonly string RewardId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Amount;
   
    public const int __ID__ = 1672915665;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "QuestId:" + QuestId + ","
        + "RewardType:" + RewardType + ","
        + "RewardId:" + RewardId + ","
        + "Amount:" + Amount + ","
        + "}";
    }
}
}

