
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 角色配置表
/// </summary>
public partial class TbAdventureCharacter
{
    private readonly System.Collections.Generic.Dictionary<string, Adventure.CharacterInfo> _dataMap;
    private readonly System.Collections.Generic.List<Adventure.CharacterInfo> _dataList;
    
    public TbAdventureCharacter(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Adventure.CharacterInfo>(count);
        _dataList = new System.Collections.Generic.List<Adventure.CharacterInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Adventure.CharacterInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Adventure.CharacterInfo.DeserializeCharacterInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CharacterId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Adventure.CharacterInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Adventure.CharacterInfo> DataList => _dataList;

    public Adventure.CharacterInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Adventure.CharacterInfo Get(string key) => _dataMap[key];
    public Adventure.CharacterInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

