
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 道具配置表
/// </summary>
public partial class TbItemInfo
{
    private readonly System.Collections.Generic.Dictionary<string, Adventure.ItemInfo> _dataMap;
    private readonly System.Collections.Generic.List<Adventure.ItemInfo> _dataList;
    
    public TbItemInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Adventure.ItemInfo>(count);
        _dataList = new System.Collections.Generic.List<Adventure.ItemInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Adventure.ItemInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Adventure.ItemInfo.DeserializeItemInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Adventure.ItemInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Adventure.ItemInfo> DataList => _dataList;

    public Adventure.ItemInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Adventure.ItemInfo Get(string key) => _dataMap[key];
    public Adventure.ItemInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

