
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 地点配置表
/// </summary>
public partial class TbLocationInfo
{
    private readonly System.Collections.Generic.Dictionary<string, Adventure.LocationInfo> _dataMap;
    private readonly System.Collections.Generic.List<Adventure.LocationInfo> _dataList;
    
    public TbLocationInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Adventure.LocationInfo>(count);
        _dataList = new System.Collections.Generic.List<Adventure.LocationInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Adventure.LocationInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Adventure.LocationInfo.DeserializeLocationInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.LocationId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Adventure.LocationInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Adventure.LocationInfo> DataList => _dataList;

    public Adventure.LocationInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Adventure.LocationInfo Get(string key) => _dataMap[key];
    public Adventure.LocationInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

