
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 任务配置表
/// </summary>
public partial class TbQuestInfo
{
    private readonly System.Collections.Generic.Dictionary<string, Adventure.QuestInfo> _dataMap;
    private readonly System.Collections.Generic.List<Adventure.QuestInfo> _dataList;
    
    public TbQuestInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<string, Adventure.QuestInfo>(count);
        _dataList = new System.Collections.Generic.List<Adventure.QuestInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Adventure.QuestInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Adventure.QuestInfo.DeserializeQuestInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.QuestId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Adventure.QuestInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Adventure.QuestInfo> DataList => _dataList;

    public Adventure.QuestInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Adventure.QuestInfo Get(string key) => _dataMap[key];
    public Adventure.QuestInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

