
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.Adventure
{
/// <summary>
/// 任务条件表
/// </summary>
public partial class TbQuestCondition
{
    private readonly System.Collections.Generic.List<Adventure.QuestConditionCfg> _dataList;


    public TbQuestCondition(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataList = new System.Collections.Generic.List<Adventure.QuestConditionCfg>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Adventure.QuestConditionCfg _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Adventure.QuestConditionCfg.DeserializeQuestConditionCfg(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<Adventure.QuestConditionCfg> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

