
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Battle.TbAbilities TbAbilities {get; }
    public Battle.TbCharacterInfo TbCharacterInfo {get; }
    public Battle.TbGuide TbGuide {get; }
    public demo.Tbitem Tbitem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbAbilities = new Battle.TbAbilities(loader("battle_tbabilities"));
        TbCharacterInfo = new Battle.TbCharacterInfo(loader("battle_tbcharacterinfo"));
        TbGuide = new Battle.TbGuide(loader("battle_tbguide"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAbilities.ResolveRef(this);
        TbCharacterInfo.ResolveRef(this);
        TbGuide.ResolveRef(this);
        Tbitem.ResolveRef(this);
    }
}

}
